apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: tod
  labels:
    app: broker-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-edge
  template:
    metadata:
      labels:
        app: broker-edge
    spec:
      containers:
      - image: localhost:5000/mqtt-broker:v1
        #      - image: eclipse-mosquitto:latest
        name: broker
        resources:
          requests:
            memory: "50Mi"
            cpu: "0.5"
          limits:
            memory: "100Mi"
            cpu: "1"
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
