apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tod-code
  namespace: tod
spec:
  storageClassName: "local-storage"
  volumeName: pv-tod-code
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
