apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-direction
  namespace: tod
  labels:
    app: ms-direction-obu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-direction-obu
  template:
    metadata:
      labels:
        app: ms-direction-obu
    spec:
      volumes:
        - name: ms-direction-code
          persistentVolumeClaim:
            claimName: pvc-tod-code
      containers:
      - image: localhost:5000/ms-tod-app:v1
        name: ms-direction
        resources:
          requests:
            memory: "50Mi"
            cpu: "0.5"
          limits:
            memory: "100Mi"
            cpu: "1"
        volumeMounts:
        - name: ms-direction-code
          mountPath: /home/tod
        env:
          - name: BROKERIP
            valueFrom:
              configMapKeyRef:
                name: ms-ip
                key: BROKERIP
          - name: BROKERPORT
            valueFrom:
              configMapKeyRef:
                name: ms-ip
                key: BROKERPORT
        args:
          - "/bin/bash"
          - "-c"
          - |
            while true; do echo sleeping; date; sleep 86400; done;
