apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: tod
data:
  mosquitto.conf: |
     # =================================================================
     # General configuration for RDS broker
     # =================================================================

     listener 1883
     persistence true
     persistence_location /mosquitto/data/
     allow_anonymous true

     # NOTE: No bridge connections are defined here. 
     # The Central broker connects to this instance externally.
